variables:

#######################################################################
# MR integration
#######################################################################

webide-define-image-tag:
  extends: .docker-image
  stage: pretooling
  rules:
    - if: '$CI_PIPELINE_SOURCE == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-frontend/ligo-ide/**/*
    - if: '$CI_PIPELINE_SOURCE == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
    - if: '$CI_PIPELINE_SOURCE == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
  script:
    - FORMATED_CI_JOB_STARTED_AT="${CI_JOB_STARTED_AT//:/-}"
    - WEBIDE_NEW_IMAGE_TAG="registry.gitlab.com/${CI_PROJECT_PATH}/ligo_webide_new:${FORMATED_CI_JOB_STARTED_AT}-${CI_COMMIT_SHORT_SHA}"
    - WEBIDE_FRONTEND_NEW_IMAGE_TAG="registry.gitlab.com/${CI_PROJECT_PATH}/ligo_webide_frontend_new:${FORMATED_CI_JOB_STARTED_AT}-${CI_COMMIT_SHORT_SHA}"
    - echo "WEBIDE_NEW_IMAGE_TAG=${WEBIDE_NEW_IMAGE_TAG}" >> webide-img-tag.env
    - echo "WEBIDE_FRONTEND_NEW_IMAGE_TAG=${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >> webide-img-tag.env
  artifacts:
    reports:
      dotenv: webide-img-tag.env

webide-new-backend-build:
  extends: .docker-image
  stage: build
  needs:
    - job: changelog
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
  script:
    - docker build tools/webide-new/ligo-webide-backend
  after_script:
    - docker image rm "${WEBIDE_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

webide-new-frontend-build:
  extends: .docker-image
  stage: build
  needs:
    - job: changelog
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-frontend/ligo-ide/**/*
        - tools/lsp/vscode-plugin/syntaxes
      when: always
  script:
    - docker buildx build --build-context syntaxes=tools/lsp/vscode-plugin/syntaxes tools/webide-new/ligo-webide-frontend/ligo-ide
  after_script:
    - docker image rm "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

#######################################################################
# dev branch integration
#######################################################################

webide-new-backend-build-and-push-backend:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true 
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
  script:
    - docker build tools/webide-new/ligo-webide-backend -t ${WEBIDE_NEW_IMAGE_TAG}
    - echo "${CI_BUILD_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_NEW_IMAGE_TAG}"
  after_script:
    - docker image rm "${WEBIDE_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

webide-new-frontend-build-and-push:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      changes:
        - tools/webide-new/ligo-webide-frontend/ligo-ide/**/*
      when: always
  script:
    - docker buildx build --build-context syntaxes=tools/lsp/vscode-plugin/syntaxes tools/webide-new/ligo-webide-frontend/ligo-ide -t ${WEBIDE_FRONTEND_NEW_IMAGE_TAG}
    - echo "${CI_BUILD_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}"
  after_script:
    - docker image rm "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true
