#######################################################################
# MR integration
#######################################################################

webide-define-image-tag:
  extends: .docker-image
  stage: pretooling
  needs:
    - job: changelog
      artifacts: false
  rules:
    - if: ($CI_MERGE_REQUEST_EVENT_TYPE == "merge_train")
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^[w;W]eb[I;i]de-/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - tools/webide-new/ligo-webide-frontend/**/*
        - tools/vscode/syntaxes
      when: always
  script:
    - FORMATED_CI_JOB_STARTED_AT="${CI_JOB_STARTED_AT//:/-}"
    - NPR_ENVIRONMENT="$(echo ${CI_MERGE_REQUEST_TITLE} | grep -io 'webide-[ab]' | head -1 | sed 's/^[wW][eE][bB][Ii][dD][eE]//')" || true
    - WEBIDE_NEW_IMAGE_TAG="registry.gitlab.com/${CI_PROJECT_PATH}/ligo_webide_new:${FORMATED_CI_JOB_STARTED_AT}-${CI_COMMIT_SHORT_SHA}${NPR_ENVIRONMENT}"
    - WEBIDE_FRONTEND_NEW_IMAGE_TAG="registry.gitlab.com/${CI_PROJECT_PATH}/ligo_webide_frontend_new:${FORMATED_CI_JOB_STARTED_AT}-${CI_COMMIT_SHORT_SHA}${NPR_ENVIRONMENT}"
    - echo "WEBIDE_NEW_IMAGE_TAG=${WEBIDE_NEW_IMAGE_TAG}" >> webide-img-tag.env
    - echo "WEBIDE_FRONTEND_NEW_IMAGE_TAG=${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >> webide-img-tag.env
  artifacts:
    reports:
      dotenv: webide-img-tag.env

webide-new-backend-build:
  extends: .docker-image
  stage: build
  needs:
    - job: changelog
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^[w;W]eb[I;i]de-/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
  script:
    - docker build tools/webide-new/ligo-webide-backend
  after_script:
    - docker image rm "${WEBIDE_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

webide-new-frontend-build:
  extends: .docker-image
  stage: build
  needs:
    - job: changelog
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^[w;W]eb[I;i]de-/'      
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - tools/webide-new/ligo-webide-frontend/ligo-ide/**/*
        - tools/vscode/syntaxes
      when: always
  script:
    - docker buildx build --build-context syntaxes=tools/vscode/syntaxes tools/webide-new/ligo-webide-frontend/ligo-ide
  after_script:
    - docker image rm "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

#######################################################################
# dev branch integration
#######################################################################

webide-new-backend-build-and-push-backend:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true 
  rules:
    - if: ($CI_MERGE_REQUEST_EVENT_TYPE == "merge_train")
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^[w;W]eb[I;i]de-/'      
      when: always
  script:
    - docker build tools/webide-new/ligo-webide-backend -t ${WEBIDE_NEW_IMAGE_TAG}
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_NEW_IMAGE_TAG}"
  after_script:
    - docker image rm "${WEBIDE_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

webide-new-frontend-build-and-push:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true
  rules:
    - if: ($CI_MERGE_REQUEST_EVENT_TYPE == "merge_train")
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^[w;W]eb[I;i]de-/'      
      when: always
  script:
    - docker buildx build --build-context syntaxes=tools/vscode/syntaxes
      --build-arg backend_url=backend.ligo-webide-v2${NPR_ENVIRONMENT}.gcp-npr.marigold.dev
      --build-arg http_protocol=https
      -f tools/webide-new/ligo-webide-frontend/ligo-ide/Dockerfile 
      tools/webide-new/ligo-webide-frontend/ligo-ide 
      -t ${WEBIDE_FRONTEND_NEW_IMAGE_TAG}
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}"
  after_script:
    - docker image rm "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}" >/dev/null 2>&1 || true

webide-new-release-backend-build-and-push:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - tools/webide-new/ligo-webide-backend/**/*
      when: always
  script:
    - docker build tools/webide-new/ligo-webide-backend -t ${WEBIDE_NEW_IMAGE_TAG}-release
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_NEW_IMAGE_TAG}-release"
  after_script:
    - docker image rm "${WEBIDE_NEW_IMAGE_TAG}-release" >/dev/null 2>&1 || true

webide-new-release-frontend-build-and-push:
  extends: .docker-image
  stage: deploy
  needs:
    - job: webide-define-image-tag
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      changes:
        - tools/webide-new/ligo-webide-frontend/**/*
        - tools/vscode/syntaxes
      when: always
  script:
    - docker buildx build --build-context syntaxes=tools/vscode/syntaxes
      --build-arg backend_url=backend.ide.ligolang.org
      --build-arg http_protocol=https
      -f tools/webide-new/ligo-webide-frontend/ligo-ide/Dockerfile 
      tools/webide-new/ligo-webide-frontend/ligo-ide 
      -t ${WEBIDE_FRONTEND_NEW_IMAGE_TAG}-release
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}-release"
  after_script:
    - docker image rm "${WEBIDE_FRONTEND_NEW_IMAGE_TAG}-release" >/dev/null 2>&1 || true
